/*
 * Copyright: 2017 dingxiang-inc.com Inc. All rights reserved.
 */

package com.dingxianginc.ctu.client.model;

public enum CtuResponseStatus {
    SUCCESS("SUCCESS"),
//    HAS_RISK("HAS_RISK"),

    INVALID_REQUEST_PARAMS("INVALID_REQUEST_PARAMS"),
    INVALID_REQUEST_BODY("INVALID_REQUEST_BODY"),
    INVALID_REQUEST_NO_EVENT_DATA("INVALID_REQUEST_NO_EVENT_DATA"),
    INVALID_REQUEST_SIGN("INVALID_REQUEST_SIGN"),
    INVALID_APP_KEY("INVALID_APP_KEY"),
    INVALID_EVENT_CODE("INVALID_EVENT_CODE"),
    INVALID_APP_EVENT_RELATION("INVALID_APP_EVENT_RELATION"),

    EVENT_GRAY_SCALE("EVENT_GRAY_SCALE"),
    NO_POLICY_FOUND("NO_POLICY_FOUND"),
    POLICY_HAS_ERROR("POLICY_HAS_ERROR"),
    NOT_SUPPORTED_POLICY_OPERATOR("NOT_SUPPORTED_POLICY_OPERATOR"),

    QPS_EXCEEDING_MAXIMUM_THRESHOLD("QPS_EXCEEDING_MAXIMUM_THRESHOLD"),
    SERVER_CONNECT_FAILED("SERVER_CONNECT_FAILED"),

    SERVICE_INTERNAL_ERROR("SERVICE_INTERNAL_ERROR"),

    NO_TRUST_IN_NAMELIST("NO_TRUST_IN_NAMELIST");

    private String statusDesc;

    private CtuResponseStatus(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    public String statusDesc() {
        return this.statusDesc;
    }
}
